// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package store

import ()

type RepliedItem struct {
	ID          int64
	ReplyID     int64
	ItemType    string
	UpdatedTime int64
}
